### ISSUE TITLE
vaultfs: Support kubernetes authentication

### ISSUE THREAD

**Issue by Joibel** [hairyhenderson/go-fsimpl#152]
I'd like to add support for https://www.vaultproject.io/docs/auth/kubernetes. This would take a role parameter, and optionally a path for where to load the service account JWT from, but this would default to the default service account mount location.

This would be a low priority auth method in the list so could be overridden. It would then allow go-fsimpl to just specify a role and then be authenticated when used within k8s containers.

I'm happy to write this if this is OK by you @hairyhenderson.

**Comment by hairyhenderson** [comment]
@Joibel wonderful, I would definitely look at a PR with this. Let me know if you have any questions!

**Comment by hairyhenderson** [comment]
I've mentioned this in #161 and alluded to it in #162 and #171, but for completeness, I've decided to instead switch to the Vault API's [`AuthMethod`](https://pkg.go.dev/github.com/hashicorp/vault/api#AuthMethod) interface, which has a Kubernetes method provided by [`github.com/hashicorp/vault/api/auth/kubernetes`](https://pkg.go.dev/github.com/hashicorp/vault/api/auth/kubernetes).

Thanks for working on this @Joibel, which was the motivation I needed to work on #171 😉
