### ISSUE TITLE
vaultfs: Detect K/V Version 2 and support version param

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/go-fsimpl#24]
Only the KV Version 1 secret engine will work out of the box (as of #19). KV Version 2 is also necessary. The added complication is the path is a bit different (there are `data/` and `metadata/` prefixes), and we need to support a `version` param.

Note that right now providing params assumes a `POST`, whereas KVv2 (uniquely?) has a `GET` API.

**Comment by hairyhenderson** [comment]
_(see also note in https://github.com/hairyhenderson/go-fsimpl/issues/10#issuecomment-869091487)_

**Comment by zhilyaev** [comment]
@hairyhenderson updates?)

**Comment by hairyhenderson** [comment]
Not yet, unfortunately. I don't use Vault very often anymore, and so this is a bit less pressing for my own use-cases. I don't think the necessary work is _that_ complex, but just needs to be done.

I would be grateful for a PR though if you're interested in contributing! 🙂

**Comment by zhilyaev** [comment]
I have 2 idea about it.

## 1

Create `vault2://` scheme.

`vault2:///secret/test` --> `vault2://secret/data/test`

## 2 

rewrite this method https://github.com/hairyhenderson/go-fsimpl/blob/main/vaultfs/vault.go#L223

And leave it as it is. `vault://secret/data/test`

**Comment by hairyhenderson** [comment]
> Create `vault2://` scheme.

That's definitely not going to work. The `vault://` scheme supports multiple secret engines, not just k/v: https://www.vaultproject.io/docs/secrets

The Vault CLI will [first check the version](https://github.com/hashicorp/vault/blob/main/command/kv_get.go#L96) before retrieving the value, so that's probably what this package will need to do as well. I don't want the user to have to know which secret engine is mounted to the path.

**Comment by Joibel** [comment]
I'm happy to look at making this 'just work' via detecting the version when I get time.

**Comment by hairyhenderson** [comment]
@Joibel that would be fantastic, I would love to see a PR for this 😁

**Comment by hairyhenderson** [comment]
I've actually started working on this - it's finicky, but not that complex... Should have a PR ready in a day or so.

**Comment by Joibel** [comment]
Nice. I'm happy to test on a real vault if you don't have one.

**Comment by hairyhenderson** [comment]
FYI @Joibel - #159 will be getting merged soon. I've tested a bunch with a Vault server in dev-mode, but perhaps there are gotchas with "real" Vault servers that you may want to test out?

There's a simple CLI in `examples/fscli` that can be used for testing too:

```console
$ go build ./examples/fscli
$ ./fscli -base-url=vault:///secret/ cat 'foo?version=1'
...
```

**Comment by Joibel** [comment]
Sorry for the delay in verifying this, I've not been at a computer for a few days. It's good and works as you'd hoped against a real v2 kv store.

**Comment by hairyhenderson** [comment]
no problem @Joibel, thanks for verifying!
