### ISSUE TITLE
specifying patch version in go.mod is a bit aggressive

### ISSUE THREAD

**Issue by rubensayshi** [hairyhenderson/go-fsimpl#634]
hey @hairyhenderson, 

by specifying the patch version in your `go.mod` file you're causing anyone using your package who isn't on the same (or newer) version to get warnings about your package not being compatible.  
if you could stick to only specifying the minor version, ie `1.22` then this would be a lot less aggressive, and effectively I think the same since there won't be any difference in language functionality between patch versions.

I noticed the reason you did this though is because you're using the version from the `go.mod` file in your CI pipeline since a recent PR you did; https://github.com/hairyhenderson/go-fsimpl/pull/563

I think the `actions/setup-go` should work just fine with specifying `1.22` though, and use the latest patch version available 🤔 ?

**Comment by hairyhenderson** [comment]
@rubensayshi I'm sorry you see this as aggressive, that's certainly not how it was intended.

Go 1.22.1, .2, and .3 all contain security fixes that may potentially impact users of this module, and IMO there's no valid reason _not_ to upgrade your toolchains ASAP.

It's also entirely up to you whether or not to upgrade to a newer version of this module.

**Comment by rubensayshi** [comment]
sorry, I didn't mean aggressive as _you_ being overly aggressive, I just meant continuously bumping to the latest version ;) 

as far as I know the intended purpose of setting a version in the `go.mod` file of a library is to indicate the _minimum_ version necessary for this module to function regarding compatibility.

though I don't disagree with upgrading asap, I just thought maybe you wouldn't want people to be forced into doing that at a faster pace then they're own upgrade schedule just to keep your library up-to-date ;)

**Comment by hairyhenderson** [comment]
I don't follow... how am I forcing people into doing anything? If you don't want the updated `go.mod`, don't bump your dependency on this module...
