### ISSUE TITLE
Build Fails on Darwin (without CGO enabled)

### ISSUE THREAD

**Issue by bbernays** [hairyhenderson/go-fsimpl#64]
A dependency of `azure-pipeline-go`  requires CGO to be enabled in order to build for Darwin

Issue in Dependency:
https://github.com/Azure/azure-pipeline-go/issues/31

Root issue:
https://github.com/mattn/go-ieproxy/issues/34

**Comment by hairyhenderson** [comment]
thanks for filing this @bbernays - will have a look!

**Comment by erezrokah** [comment]
Hi 👋 Thanks for this fix. Is it possible that https://github.com/hairyhenderson/go-fsimpl/commit/18c19dd9fe62d12a268c72319ba6f4ab89dc852e#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R99 re-introduced the issue? See https://github.com/cloudquery/cloudquery/pull/950 and https://github.com/cloudquery/cloudquery/runs/6963839056?check_suite_focus=true

**Comment by hairyhenderson** [comment]
hmm... yes that is possible. Sorry about this @erezrokah. I'll try to get that fixed soon!

**Comment by erezrokah** [comment]
Thanks @hairyhenderson! Appreciate the super quick reply and you taking the time to look into it 👍
