### ISSUE TITLE
AWS Parameter Store (`aws+smp`) support

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/go-fsimpl#7]

**Comment by iamralch** [comment]
@hairyhenderson are you working on this? Any ETA?

**Comment by hairyhenderson** [comment]
@iamralch Thanks for the reminder, I'd actually forgotten that I hadn't added this yet 😅

I don't have a lot of spare bandwidth right now, but will attempt to spend time on this over the next couple weeks.

**Comment by iamralch** [comment]
Thank you for your quick reply. Appreciate!
