### ISSUE TITLE
Promote filefs to stock Go

### ISSUE THREAD

**Issue by mcandre** [hairyhenderson/go-fsimpl#809]
Thank you for implementing a `file://` handler for fs.FS URL's.

I find it ridiculous that Go fails to implement fs.FS for the local filesystem.

Petition to promote such an implementation directly into the Go standard library.

**Comment by hairyhenderson** [comment]
@mcandre this isn't the place for such a request - I'm not associated with the Go development team and it's unlikely that this will go anywhere.

See https://github.com/golang/proposal#readme for the right way to propose adding things to the Go standard library!
