### ISSUE TITLE
Implement a more generic constructor for rootfs

### ISSUE THREAD

**Issue by mcandre** [hairyhenderson/go-fsimpl#810]
`os.DirFs(pth)` seems to have a fatal design flaw: It invites the user to hardcode either a UNIX (e.g., `/`) or Windows (e.g., `C:`) root directory name.

Please implement a 0-ary constructor for filefs that automatically selects an appropriate root directory name in an operating system independent way.

Note that Cygwin environments can reasonably follow UNIX conventions (`/`); It's not the executable platform so much as the runtime environment.

**Comment by hairyhenderson** [comment]
Thanks for this suggestion - can you give me a concrete example of how you imagine this might look? I'm not sure I'm totally following what the concern is...
